import { Box, VStack, Text, chakra, Grid } from "@chakra-ui/react";
import Head from "next/head";
import { workType, aboutUsBanner, EngineersData } from "../config/data";
import ContactUs from "../@components/contact/ContactUs";
import "react-multi-carousel/lib/styles.css";
import { AiFillPlayCircle } from "react-icons/ai";
import AboutBanner from "../@components/aboutUs/AboutBanner";
import Engineers from "../@components/aboutUs/Engineers";

import client from "../apollo-client";
import { aboutUsData, footer, homeData,navbar } from "./../graphql/queries";
import { Key } from "react";

const AboutUs = (props: any) => {
  return (
    <Box>
      <Head>
        <title>Serices ASAP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box px={10} py="15rem">
        <VStack>
          <Text
            lineHeight="38.5px"
            textAlign="center"
            position="relative"
            fontSize={{ md: 56, base: 30 }}
            fontWeight={600}
            letterSpacing={0}
            color="#444"
          >
            {props?.aboutus?.attributes?.heading[0].preHeading}
            <chakra.span
              ml={{ md: 3, base: 1 }}
              lineHeight={0.8}
              display="inline-block"
              borderBottom="10px solid"
              borderColor="ared.100"
            >
              {props?.aboutus?.attributes?.heading[0].underlineHeading}
            </chakra.span>
            {props?.aboutus?.attributes?.heading[0].postHeading}
          </Text>
          <Text
            lineHeight="38.5px"
            textAlign="center"
            position="relative"
            fontSize={18}
            fontWeight={600}
            letterSpacing={0}
            color="#444"
          >
            {props?.aboutus?.attributes?.text}
          </Text>
          <Box>
            {props?.aboutus?.attributes?.isVideo && (
              <Box
                as={AiFillPlayCircle}
                mt={5}
                size="60px"
                _hover={{
                  transform: "scale(1.2)",
                  transition: "all 1s",
                }}
                cursor="pointer"
                color="ared.100"
              />
            )}
          </Box>
        </VStack>
      </Box>

      <Box px="8vw">
        <Grid templateColumns={{ base: "repeat(1, 1fr)", md: "repeat(2, 1fr)", lg: "repeat(4, 1fr)" }} gap={8}>
          {props?.aboutus?.attributes?.objective.map((objectiveText: any, index: Key) => (
            <Box
              key={index}
              w="100%"
              bg="#ffffff"
              py={{ md: 16, base: 16 }}
              borderRadius="5px"
              justifyContent="center"
              display="flex"
              boxShadow="0 10px 20px rgb(0 0 0 / 8%), 0 13px 20px rgb(0 0 0 / 8%)"
            >
              <Text textAlign="center" lineHeight="22px" color="#42424f" fontWeight={600} width="70%" fontSize={18}>
                {objectiveText?.objectiveText}
              </Text>
            </Box>
          ))}
        </Grid>
      </Box>

      <AboutBanner
        text={props?.aboutus?.attributes?.banner?.text}
        heading1={props?.aboutus?.attributes?.banner?.heading?.preHeading}
        underlineHeading={props?.aboutus?.attributes?.banner?.heading?.underlineHeading}
        heading2={props?.aboutus?.attributes?.banner?.heading?.postHeading}
        image={props?.aboutus?.attributes?.banner?.image}
      />

      <Engineers engineers={props?.aboutus?.attributes?.engineers!} />

      <Box mt={24}>
        <ContactUs
          heading={props?.home?.attributes?.contactTitle}
          text={props?.home?.attributes?.contactText}
          name={props?.home?.attributes?.contact[0].name}
          email={props?.home?.attributes?.contact[0].email}
          phone={props?.home?.attributes?.contact[0].phone}
          tellMore={props?.home?.attributes?.contact[0].tellMore}
        />
      </Box>
    </Box>
  );
};

export async function getServerSideProps() {
  const { data: aboutData } = await client.query({
    query: aboutUsData,
  });
  const { data: homePageData } = await client.query({
    query: homeData,
  });
  const { data: navbarData } = await client.query({
    query: navbar,
  });
  const { data: footerData } = await client.query({
    query: footer,
  });


  return {
    props: {
      aboutus: aboutData.aboutus.data,
      navbar: navbarData.navbar.data,
      home: homePageData.home.data,
      footer: footerData.footer.data,
    },
  };
}

export default AboutUs;
