import { Box } from "@chakra-ui/react";
import Head from "next/head";
import Section1 from "../@components/contact/Section1";
import Section2 from "../@components/contact/Section2";

import client from "../apollo-client";
import { footer, homeData, navbar, contactUs } from "./../graphql/queries";
const Contact = (props) => {
  const { attributes: data } = props.contact;
  console.log(data);
  return (
    <Box>
      <Head>
        <title>Contact us page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section1 heading={data.heading} text={data.text} />
      {console.log(props)}
      <Section2
        name={data?.contactForm?.name}
        email={data?.contactForm?.email}
        phone={data?.contactForm?.phone}
        tellMore={data?.contactForm?.tellMore}
        address={props?.footer?.attributes?.address}
        address2={props?.footer?.attributes?.address2}
      />
    </Box>
  );
};
export async function getServerSideProps() {
  const { data: homePageData } = await client.query({
    query: homeData,
  });
  const { data: navbarData } = await client.query({
    query: navbar,
  });
  const { data: footerData } = await client.query({
    query: footer,
  });
  const { data: contactData } = await client.query({
    query: contactUs,
  });

  return {
    props: {
      home: homePageData.home.data,
      navbar: navbarData.navbar.data,
      footer: footerData.footer.data,
      contact: contactData.contactus.data,
    },
  };
}
export default Contact;
