import { Box } from "@chakra-ui/react";
import Head from "next/head";
import Section1 from "../@components/work/Section1";
import Section2 from "../@components/work/Section2";
import client from "../apollo-client";
import ContactUs from "../@components/contact/ContactUs";

import { footer, homeData, navbar, works } from "./../graphql/queries";

const Work = (props) => {
  const { attributes: data } = props.work;
  return (
    <Box>
      <Head>
        <title>work page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section1 heading={data?.heading} button={data?.button} />
      <Section2 works={data?.works} />
      <Box mt={24}>
        <ContactUs
          heading={props?.home?.attributes?.contactTitle}
          text={props?.home?.attributes?.contactText}
          name={props?.home?.attributes?.contact[0].name}
          email={props?.home?.attributes?.contact[0].email}
          phone={props?.home?.attributes?.contact[0].phone}
          tellMore={props?.home?.attributes?.contact[0].tellMore}
        />
      </Box>
      
    </Box>
  );
};

export async function getServerSideProps() {
  const { data: homePageData } = await client.query({
    query: homeData,
  });
  const { data: navbarData } = await client.query({
    query: navbar,
  });
  const { data: footerData } = await client.query({
    query: footer,
  });
  const { data: workData } = await client.query({
    query: works,
  });

  return {
    props: {
      home: homePageData.home.data,
      navbar: navbarData.navbar.data,
      footer: footerData.footer.data,
      work: workData.work.data,
    },
  };
}

export default Work;
