import { Box } from "@chakra-ui/react";
import Head from "next/head";
import BlogDetail from "../../@components/blogPage/BlogDetail";
import RelatedPost from "../../@components/blogPage/BlogDetail/relatedPost";
import client from "../../apollo-client";
import { footer, homeData, navbar, blogById } from "../../graphql/queries";

const Blogs = (props: any) => {
  const { attributes: data } = props.blogData;
  return (
    <Box>
      <Head>
        <title>Single Blog detail page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bgColor={"white"}>
        <BlogDetail blogData={data} />
      </Box>
      <RelatedPost />
    </Box>
  );
};

export async function getServerSideProps({ query }: any) {
  const { id } = query;
  const { data: navbarData } = await client.query({
    query: navbar,
  });
  const { data: footerData } = await client.query({
    query: footer,
  });
  const { data: blogData } = await client.query({
    query: blogById,
    variables: { id: id },
  });

  return {
    props: {
      navbar: navbarData.navbar.data,
      footer: footerData.footer.data,
      blogData: blogData.blog.data,
    },
  };
}
export default Blogs;
